### ISSUE TITLE
Feature Request -- GWT 2.5 Closure Compiler (optional flag set)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [mvp4g/mvp4g#114]
```
See 
https://developers.google.com/web-toolkit/doc/latest/ReleaseNotes#optimization

Would like to request that MVP4G allow for setting this flag either by default 
or optionally.  It does have a penalty in that it will further slow down how 
long it takes to compile client-side code.


```

Original issue reported on code.google.com by `fastnsil...@gmail.com` on 28 Jun 2012 at 4:53

**Comment by mvp4g** [comment]
Closure compiler has been removed from GWT 2.8.0 (see: [https://groups.google.com/forum/#!topic/Google-Web-Toolkit/k_kjIv9Klsg](https://groups.google.com/forum/#!topic/Google-Web-Toolkit/k_kjIv9Klsg))

closed
