### ISSUE TITLE
Question: Is it possible to create an EventHandler which only produces events?

### ISSUE THREAD

**Issue by dharezlak** [mvp4g/mvp4g#127]
Such event handler is never listed in the @Event annotation of any event bus. Simple experiments showed that such handler (@EventHandler annotated class) is never picked up by mvp4g's initialization process.

**Comment by FrankHossfeld** [comment]
Please, can you provide an example of what you want to do?

**Comment by dharezlak** [comment]
I would like to implement an EventHandler which only produces events (does not implement any `on...` methods hence is not listed anywhere in the `MyEventBus`):

```
@EventHandler
public class EventProducer extends BaseEventHandler<MyEventBus> {

	public EventProducer() {
		registerGlobalBrowserHandlers(this::handleGlobalBrowserEvent);
	}

	private void handleGlobalBrowserEvent(Event event) {
		getEventBus().pushEvent(event);
	}
}
```

Currently, I have to create a dummy event in `MyEventBus` so that my producer (implementing a onDummy method) is registered with mvp4g. Is there a way to cleanly register such event handlers?

**Comment by FrankHossfeld** [comment]
Try:

```
@Start
@Event(bind = { EventProducer.class })
void start();
```

This should work.

**Comment by dharezlak** [comment]
Yes, it works. Thanks!
