### ISSUE TITLE
Compatibilité with gwtpishstate on gwt 2.7.0

### ISSUE THREAD

**Issue by amanzo-yseop** [mvp4g/mvp4g#128]
We’re working on a project based on GWT 2.6.1, mvp4g 1.4 and the library gwt-pushstate 1.0.0 for the history/urls management.
Now, We’re trying to migrate on GWT 2.7.0. The library gwtpushstate 1.0.0 doesn’t work and we need to use the corresponding Wallis library (https://github.com/rdwallis/gwt-pushstate). For that, as indicated, we replaced all uses of History class with the Historian interface.    
At the same time, we migrated to mvp4g 1.5, but it also uses the History class. So, this library is incompatible with that of Wallis and we have a run time error.
We can adapt your classes to our needs, but perhaps you have a better recommendation.
So, what do you suggest?

**Comment by mvp4g** [comment]
I don't know gwt-pushstate. Do you have a small sample project that shows how gwt-pushstate works?  This would help to see what we can change in mvp4g to get it wort without having trouble with the current implementation. And, if you know, what you have to change, can you provide this changes?

**Comment by amanzo-yseop** [comment]
I debugged mvp4g and I came to the conclusion the only class impacted for the compatibility with gwt-pushstate is [DefaultHistoryProxy.java](https://github.com/mvp4g/mvp4g/blob/1.5.0/sources/src/main/java/com/mvp4g/client/history/DefaultHistoryProxy.java).
As suggested here:
https://github.com/rdwallis/gwt-pushstate
essentially I replaced History with Historian and it works fine.
The problem is this class has a private constructor (it is a Singleton) and I can't extend it.
So, it seems to me I can't use the same jar and I have to create a custom "mvp4g-gwt-pushstate" jar.
If not, what do you suggests?

**Comment by mvp4g** [comment]
That's correct. The only class inside mvp4g which uses the History class is the DefaultHistoryProxy.java.

The DefaultHistoryProxy class is used at two places in mvp4g. I think, we could do something like this:

Add a new attribute to the @Events annotation. For example 'historyProxy'. The default value could be 'DefaultHistoryProxy.class'. This opens up the possibility to replace the DefaultHistoryProxy with another one. Inside mvp4g the current DefaultHistoryProxy  has to be replaced by a HistoryProxyFactory which will return an instance of the class defined with historyProxy attribute.

What do you think?

**Comment by amanzo-yseop** [comment]
Yes, it seems a very good idea. 
How long do you think it would take? 
/cc @lpetit-yseop

**Comment by mvp4g** [comment]
I hope to provide a SNAPSHOT next week, so we can start testing the new feature. Are you willing to provide a sample implementation of the HistoryProxy using get-pushstate, which I can add to the documentation for the next release?

**Comment by amanzo-yseop** [comment]
The following is the DefaultHistoryProxy class we adapted to work with gwt-pushstate:
`package com.mvp4g.client.history;

import com.google.gwt.core.shared.GWT;
import com.google.gwt.event.logical.shared.HasValueChangeHandlers;
import com.google.gwt.event.logical.shared.ValueChangeEvent;
import com.google.gwt.event.logical.shared.ValueChangeHandler;
import com.google.gwt.event.shared.GwtEvent;
import com.google.gwt.event.shared.HandlerManager;
import com.google.gwt.event.shared.HandlerRegistration;
import com.google.gwt.place.shared.PlaceHistoryHandler.Historian;

public class DefaultHistoryProxy implements HistoryProxy {
    private static class HistoryEventSource implements
            HasValueChangeHandlers<String> {

        private HandlerManager handlers = new HandlerManager(null);

        @Override
        public void fireEvent(GwtEvent<?> event) {
            handlers.fireEvent(event);
        }

        @Override
        public HandlerRegistration addValueChangeHandler(
                ValueChangeHandler<String> handler) {
            return handlers.addHandler(ValueChangeEvent.getType(), handler);
        }

        public void fireValueChangedEvent(String newToken) {
            ValueChangeEvent.fire(this, newToken);
        }
    }

    public static final DefaultHistoryProxy INSTANCE = new DefaultHistoryProxy();

    private final static Historian HISTORIAN = GWT.create(Historian.class);

    private static HistoryEventSource historyEventSource = new HistoryEventSource();

    private DefaultHistoryProxy() {
        // this class is a singleton
    }

    public HandlerRegistration addValueChangeHandler(
            ValueChangeHandler<String> handler) {
        return HISTORIAN.addValueChangeHandler(handler);
    }

    public void fireCurrentHistoryState() {
        String currentToken = getToken();
        historyEventSource.fireValueChangedEvent(currentToken);
    }

    public String getToken() {
        return HISTORIAN.getToken();
    }

    public void newItem(String historyToken) {
        HISTORIAN.newItem(historyToken, true);
    }

    public void newItem(String historyToken, boolean issueEvent) {
        HISTORIAN.newItem(historyToken, issueEvent);
    }

    public native void forward() /*-{
                                    $wnd.history.forward();
                                    }-*/;

    public native void back() /*-{
                                $wnd.history.back();
                                }-*/;
}
`
/cc @lpetit-yseop

**Comment by mvp4g** [comment]
I have added a new attribute to the @Events annotation (historyProxy). 
```
@Events(startPresenter = MyStartPresenter.class,
        historyProxy = CustomHistoryProxy.class,
        .....
```
if you need to access the instance of the HIstoryProxy class, use:
```
HistoryProxyProvider.INSTANCE.get()
```
**Important note:** 
The CustomHistoryProxy class needs a public zero argument constructor. Also, there it is no longer necessary, that this class is a singleton!

I have successfully tested history with the default implementation. 

Please, fork the changes, build the version and test it.

**Comment by amanzo-yseop** [comment]
Yes, we'll try, but there is the following compilation's error:

[ERROR] /home/amanzo/Downloads/mvp4g-master/src/test/java/com/mvp4g/client/test_tools/HistoryProxyStub.java:[13,9] method does not override or implement a method from a supertype.

In fact, the supertype is the HistoryProxy interface who don't have the public HistoryProxy get() method.

**Comment by mvp4g** [comment]
Yes, you are right. I have removed the get()-method from the class HistoryProxyStub and updated the project. 

Don't know, why the maven build did not find show this error. 

Please try again.

**Comment by amanzo-yseop** [comment]
Yes. Not it works fine.
Can you deploy the artifact, so we can reference it in our pom.xml?
Many thanks in advance.

**Comment by mvp4g** [comment]
I have tag the version and created a release. Will see, that I get it soon to maven central.
