### ISSUE TITLE
Not calling HistoryProxyProvider when starting the module

### ISSUE THREAD

**Issue by eborel-yseop** [mvp4g/mvp4g#130]
Hello, 

I have a follow up on [this issue](https://github.com/mvp4g/mvp4g/issues/128). 

When starting the mvp4g module, a call is made to `History.fireCurrentHistoryState()`, which bypass the implementation provided by the historyProxy parameter (and in my case causes inconsistencies with the token when reloading my application)

The code is generated from `mvp4g/rebind/Mvp4gConfigurationFileWriter.java`, line 1457: 

`sourceWriter.println("History.fireCurrentHistoryState();");`

Replacing it by `HistoryProxyProvider.INSTANCE.get().fireCurrentHistoryState();` fixes my problem entirely.

Am I correct assuming this is just an oversight and not the desired implementation ?

**Comment by mvp4g** [comment]
I think, you are right. It looks like I missed this one. Will soon provide an update. 

Are willing to test it?

**Comment by eborel-yseop** [comment]
Absolutely, thank you for your reactivity.

**Comment by mvp4g** [comment]
Just updated the project and created a snapshot. I also updated some tests and search for more usages of the History class. Think, I have found them all. Made a lot of test and everything works.

Plaese, create a snapshot and test it.

**Comment by eborel-yseop** [comment]
I have created a snapshot based on your last update, and I can confirm that the problem is fixed.

Thanks again !

**Comment by mvp4g** [comment]
Great! Hope to get the release done this week!

**Comment by mvp4g** [comment]
complete

**Comment by mvp4g** [comment]
Please can you test this [SNAPSHOT](http://www.gishmo.de/public/download/mvp4g-1.5.3-SNAPSHOT.jar) against your project. There is a bug in mvp4g that applications without history will [crash](https://github.com/mvp4g/mvp4g/issues/131).

**Comment by eborel-yseop** [comment]
Hello, no problem on my end with this snapshot :+1:

**Comment by FrankHossfeld** [comment]
Thanks for testing!
