### ISSUE TITLE
"A framework to build a gwt application the right way"

### ISSUE THREAD

**Issue by amihaiemil** [mvp4g/mvp4g#132]
Someone, a long time ago, decided it was a good idea to use this framework + GWT for our apps. 
To give you a short overview: the code is a mess because of it - **the definition of spaghetti code**. 

* Interfaces (without actual implementations) and annotations everywhere, you can't even navigate in your IDE to find implementations and figure stuff out; 
* cannot open any call hierachy, on any method; 
* naming conventions which no one knows but the author of mvp4g and maybe God etc.

**What the fuck is an "event bus"?** Could you have thought of a more generic and obscure name? 

I just spent an entire day (!!!) trying to figure out how to refresh a damn widget and I'm still not sure I found the solution.

So this is about how good GWT and this framework are.
You should close this repo.

Rant over, thanks for reading.
Mihai

**Comment by mvp4g** [comment]
Hi Mihai,

I am very sorry to read that you are running in trouble with your GWT ans mvp4g-Programming. 
mvp4g implements the ideas of Ray Ryan (Google) for writing large applications with GWT. Similar like other frameworks, f.e.: GWT-Platform or native GWT. All these frameworks/patterns try to help you to write readable and maintainable applications. It does not prevent you, to write unmaintainable applications.

There is only one naming convention in mvp4g. This convention belongs to the name of the methods in the presenter which handles the event. This things are well documented inside the wiki. 

So, I am sorry to read this, but will not close this repro because there are many GWT programmers outside which writes awesome application with GWT. And some of them use mvp4g very successfully.

Bye bye,
Frank

**Comment by amihaiemil** [comment]
@mvp4g Now that I calmed down a little, let me tell you that a framework should be **king** on the app that uses it. That basically means that you, as the designer of it, should know how an app written with it looks. It is not up to the developers to decide how their code will look like, it's up to you.

You should have control over what abstractions the user makes in order to use it, guide him.
You should **dictate** what interfaces are implemented, which methods are called and in what order. 
I wrote about it in more detail [here](http://www.baeldung.com/design-a-user-friendly-java-library).

On the other hand, GWT and mvp4g simply throw some interfaces and annotations and a wiki on how to wire them together. The framework should also do that wiring... otherwise you end up with really a lot of mess.

**Comment by mvp4g** [comment]
I don't agree. 

mvp4g helps you to implement the mvp pattern and to decouple your application. It does not have a widget system nor a server communication part. It is up to you to decide which widget system and server communication pattern  to use. mvp4g is flexible enough to corporate with every widget system  and server communication. 

Also, mvp4g offers you several ways to implement the mvp-pattern. mvp4g should never the king of the application. That would make mp4g inflexible for many use cases.

> Please can you explain, what you mean with: 
> On the other hand, GWT and mvp4g simply throw some interfaces and annotations and a wiki on how to wire them together. The framework should also do that wiring... otherwise you end up with really a lot of mess.

**Comment by amihaiemil** [comment]
> On the other hand, GWT and mvp4g simply throw some interfaces and annotations and a wiki on how to wire them together. The framework should also do that wiring... otherwise you end up with really a lot of mess.

Well, that's what it seems to me. A bunch of interfaces (e.g. Button, Widget, Navigation etc) which you have to implement, in order for the GWT compiler to find your objects and turn them into JS. 

And by "should also do the wiring" I meant exactly that it should be king. It should decide 
  * what and where it's called, 
  * which exactly is the presenter and which one is the view,
  * maybe forbid dependency cycles between views and presenters (I have that in these apps. view <-> presenter) 
 * **at least** there should be a mechanism for view objects to be updated automatically. Here was my scenario (which I fixed in 2.5 days): 

   -  I have **view A** which is displayed on its own first, and then also displayed (nested) on the upcoming views B and C
   - The presenter of view B was changing data displayed on view A and view A **was not being updated**
   - But view A was the same object, the same instance everywhere, so somehow it should be automatically responsive to the changes of the data that it displays. I searched for 2 days for the method which did that refresh, navigating from class to class, only finding interfaces and annotations. Because the actual implementations were somewhere else... Anyway, not to mention you need to wait for the full moon in order to be able to debug GWT (there is some development plugin, only running on some deprecated version of Mozzila etc). 

My point is that all this is **too verbose** and I bet the talent pool for this is already close to 0.

**Comment by mvp4g** [comment]
Do you know this presentation:
[Best Practices for Architecting GWT App](https://www.youtube.com/watch?v=PDuhR18-EdM)
If not, you should spent some time watching it.

Also, nowadays, we use [SuperDevMode](http://www.gwtproject.org/articles/superdevmode.html) in GWT. With SuperDevMode there is no need to install a Plugin in the browser. All the browser has to support is Source Mapping. (Chrome does it best).

Hope that helps.

**Comment by amihaiemil** [comment]
Thanks, I'll have a look.
