### ISSUE TITLE
gwt 2.9.0 support?

### ISSUE THREAD

**Issue by rov63rus** [mvp4g/mvp4g#134]
I am using mvp4g 1.5.3 and switching to gwt 2.9.0.
I see in on gradle runtime/testRuntime dependecies graph:

+--- com.googlecode.mvp4g:mvp4g:1.5.3
|    +--- **com.google.gwt:gwt-servlet:2.8.2**
|    \--- com.google.gwt.inject:gin:2.1.2
|         +--- com.google.inject:guice:3.0
|         |    +--- javax.inject:javax.inject:1
|         |    +--- aopalliance:aopalliance:1.0
|         |    \--- org.sonatype.sisu.inject:cglib:2.2.1-v20090111
|         |         \--- asm:asm:3.1
|         \--- com.google.inject.extensions:guice-assistedinject:3.0
|              \--- com.google.inject:guice:3.0 (*)

How can I avoid that  gwt-servlet:2.8.2  dependency?

**Comment by FrankHossfeld** [comment]
Just pushed a 1.6.0-SNAPSHOT to sona.

Please test.

**Comment by FrankHossfeld** [comment]
done
